# Generated by Django 3.0.2 on 2020-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dono',
            name='endereco',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dono',
            name='telefone',
            field=models.CharField(default=465654456, max_length=11),
            preserve_default=False,
        ),
    ]
