# Generated by Django 3.0.2 on 2020-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatinho', '0005_auto_20200115_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatinho',
            name='cor',
            field=models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PARDO', 'Pardo'), ('cinza', 'cinza'), ('laranja', 'laranja'), ('bege', 'bege'), ('tricolor', 'tricolor')], max_length=100),
        ),
    ]
