# Generated by Django 3.0.2 on 2020-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dono', '0002_auto_20200113_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('porte', models.CharField(max_length=255)),
                ('cor', models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PARDO', 'Pardo')], max_length=100)),
                ('dono', models.ManyToManyField(null=True, to='dono.Dono')),
            ],
        ),
    ]
